// Generated by CoffeeScript 1.3.3
(function() {

  Object.defineProperty(Number.prototype, "ms", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 0 + this;
    }
  });

  Object.defineProperty(Number.prototype, "second", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 1000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "seconds", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 1000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "sec", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 1000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "minute", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 60000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "minutes", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 60000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "min", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 60000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "hour", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 3600000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "hours", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 3600000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "day", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 86400000 * this;
    }
  });

  Object.defineProperty(Number.prototype, "days", {
    enumerable: false,
    configurable: false,
    get: function() {
      return 86400000 * this;
    }
  });

}).call(this);
